title: "Aabhaas Vaish"
url: "https://aabhaas-vaish.github.io"
baseurl: ""

markdown: kramdown

tracking_id: UA-164588930-1

sass:
    style: compressed
    sass_dir: _sass

theme: jekyll-theme-minimal
